#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

bash scripts/release_gate_local.sh

rm -rf artifacts/redteam
python3 redteam/run.py proxy-probe \
  --corpora \
    redteam/corpora/prompt_injection.jsonl \
    redteam/corpora/jailbreak.jsonl \
    redteam/corpora/indirect_prompt_injection.jsonl \
    redteam/corpora/encoded_bypass.jsonl \
    redteam/corpora/schema_poisoning.jsonl \
    redteam/corpora/report_fabrication.jsonl \
    redteam/corpora/benign_control.jsonl \
  --out artifacts/redteam/proxy-probe-results.jsonl \
  --summary-out artifacts/redteam/proxy-probe-summary.json \
  --fail-on-fail

BUNDLE="artifacts/contest-bundle"
rm -rf "$BUNDLE"
mkdir -p "$BUNDLE"

cp README.md "$BUNDLE/README.md"
cp SUBMISSION.md "$BUNDLE/SUBMISSION.md"
cp -R docs "$BUNDLE/docs"
cp -R scenarios "$BUNDLE/scenarios"
cp -R redteam "$BUNDLE/redteam"
cp -R schemas "$BUNDLE/schemas"

mkdir -p "$BUNDLE/reports"
cp artifacts/reports/contest-report.md "$BUNDLE/reports/contest-report.md"
cp -R artifacts/demo "$BUNDLE/demo"
cp artifacts/demo/reviewer-console.html "$BUNDLE/reviewer-console.html"

if [ -d artifacts/redteam ]; then
  cp -R artifacts/redteam "$BUNDLE/redteam-results"
fi

python3 - <<'PY'
import json
import pathlib

bundle = pathlib.Path("artifacts/contest-bundle")
scenario_count = sum(1 for p in (bundle / "scenarios").iterdir() if p.is_dir())

summary_path = pathlib.Path("artifacts/redteam/proxy-probe-summary.json")
summary = json.loads(summary_path.read_text(encoding="utf-8")) if summary_path.exists() else {}
redteam = {
    "summary": "redteam-results/proxy-probe-summary.json",
    "results": "redteam-results/proxy-probe-results.jsonl",
    "total": summary.get("total"),
    "pass": summary.get("pass"),
    "fail": summary.get("fail"),
    "skip": summary.get("skip"),
}

manifest = {
    "project": "runwarden",
    "bundle_type": "contest_submission",
    "scenario_count": scenario_count,
    "required_artifacts": {
        "submission": "SUBMISSION.md",
        "report": "reports/contest-report.md",
        "reviewer_console": "reviewer-console.html",
        "scenarios": "scenarios/",
        "redteam": "redteam/",
        "redteam_results": "redteam-results/",
    },
    "redteam_proxy_probe": redteam,
    "generated_by": "scripts/contest_bundle.sh",
}

(bundle / "manifest.json").write_text(
    json.dumps(manifest, indent=2, ensure_ascii=False) + "\n",
    encoding="utf-8",
)

summary_md_path = bundle / "redteam-results" / "SUMMARY.md"
summary_md_path.parent.mkdir(parents=True, exist_ok=True)
if summary_path.exists():
    summary_md = f"""# Proxy Probe Summary

| Metric | Value |
| --- | ---: |
| total | {summary.get("total", "N/A")} |
| pass | {summary.get("pass", "N/A")} |
| fail | {summary.get("fail", "N/A")} |
| skip | {summary.get("skip", "N/A")} |

Generated by `scripts/contest_bundle.sh` from `proxy-probe-summary.json`.
"""
else:
    summary_md = """# Proxy Probe Summary

proxy-probe was not run. Execute `bash scripts/contest_bundle.sh` to generate results.
"""
summary_md_path.write_text(summary_md, encoding="utf-8")
PY

if find "$BUNDLE" -name ".env" -print -quit | grep -q .; then
  echo "contest bundle contains .env" >&2
  exit 1
fi
if find "$BUNDLE" \( -name "target" -o -name "node_modules" \) -print -quit | grep -q .; then
  echo "contest bundle contains build output" >&2
  exit 1
fi
if grep -R "sk-[A-Za-z0-9_-]\\{16,\\}" "$BUNDLE" >/dev/null 2>&1; then
  echo "contest bundle contains an API-key-looking token" >&2
  exit 1
fi

(
  cd "$BUNDLE"
  find . -type f -print0 | sort -z | xargs -0 sha256sum > SHA256SUMS
)

echo "contest bundle -> $BUNDLE"
